---
- name: install operators
  hosts: localhost
  vars:
    manifests_dir: "{{ lookup('env','GITHUB_WORKSPACE') }}/manifests"
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') }}"
    ansible_python_interpreter: /usr/bin/python3
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  pre_tasks:
    - name: Create directory for all manifests
      file:
        path: "{{ manifests_dir }}"
        state: directory
        mode: 0644

    - name: Get output from pip show openshift command
      command: pip show openshift
      ignore_errors: true
      changed_when: false
      register: reg_pip_module_openshift_installed

    - name: Set fact for openshift module
      set_fact:
        pip_module_openshift_installed: "{{ reg_pip_module_openshift_installed.rc }}"

  tasks:
    - name: Include install_operators role
      include_role:
        name: install_operator
      vars:
        operator_name: "{{ operators_var.name }}"
        operator_namespace: "{{ operators_var.namespace }}"
      loop:
        - {name: openshift-gitops-operator, namespace: openshift-operators}
        - {name: dynatrace-operator, namespace: dynatrace}
        - {name: compliance-operator, namespace: openshift-compliance}
        - {name: serverless-operator, namespace: openshift-serverless}
        - {name: mtc-operator, namespace: openshift-migration}
      loop_control:
        loop_var: operators_var
