---
- name: Run ansible playbook
  hosts: localhost
  vars:
    OPERATOR_NAME: nginx-ingress-operator
    NAMESPACE: openshift-operators
    ansible_python_interpreter: /usr/bin/python3roles:- Deploy-Operator
  roles:
    - common
