---

- name: patch cluster to Disable Master Scheduling with k8s module
  block:
    - name: patch cluster to disable master scheduling with k8s module
      k8s:
        state: present
        wait: true
        definition:
          apiVersion: config.openshift.io/v1
          kind: Scheduler
          metadata:
            name: cluster
          spec:
            mastersSchedulable: false

  when:
    - pip_module_openshift_installed  == "0"

- name: patch cluster to Disable Master Scheduling with raw commands
  block:
    - name: patch cluster to disable master scheduling with raw commands
      command: "oc patch --type=merge --patch='{\"spec\":{\"mastersSchedulable\": false }}' schedulers.config.openshift.io cluster"

  when:
    - pip_module_openshift_installed  != "0"
