name: Run ansible code 
on:
  push:
    branches:
      - 'main'
    paths:
      - 'main.yaml'
jobs:
  Setup:
    name: Setup Ansible Runner
    runs-on: ubuntu-latest
    steps:
      - name: Get the goodies
        uses: actions/checkout@main
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "4"
          oc: "4"
          

          
      - name: Deploy operator
        run: |
          echo "${{ secrets.KUBECONFIG }}" >> $GITHUB_WORKSPACE/kubeconfig
          ansible-playbook main.yaml --extra-vars KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
